sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t adnanwaheed/docker-react .

script:
  - docker run -e CI=1 adnanwaheed/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-405165580412"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
